// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/content': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content.get').default>>>>
    }
    '/api/content/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content/[slug].get').default>>>>
    }
    '/api/pdf': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pdf.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}